name: build-release-deploy
on:
  push:
    branches:
      - staging

jobs:
  build-release:
    uses: mailprotector/workflows/.github/workflows/build-ecr-single.yml@main
    strategy:
      matrix:
        aws-region: [us-east-1]
    with:
      ECR_REPOSITORY: fluentbit
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.STAGING_IAM_ROLE_ARN }}
      AWS_REGION: ${{ matrix.aws-region }}
