name: build-release-deploy
on:
  push:
    branches:
      - main

jobs:
  build-release:
    uses: mailprotector/workflows/.github/workflows/docker-build-ecr.yml@main
    with:
      build_env: production
      ECR_REPOSITORY: fluentbit
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION_1 }}
      AWS_REGION_2: ${{ secrets.AWS_REGION_2 }}
