name: build-release-deploy
on:
  push:
    branches:
      - staging

jobs:
  build-release:
    uses: mailprotector/workflows/.github/workflows/docker-build-ecr.yml@main
    with:
      build_env: staging
      ECR_REPOSITORY: fluentbit
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION_1 }}
